services:
  db:
    ports:
      - 5432:5432
    container_name: db_container
    image: postgres
    environment:
      - POSTGRES_DB=budgee_db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    volumes:
      - C:\postgres_datapart:/var/lib/postgresql/data
    restart: always

  backend:
    build: .
    container_name: api_container
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/budgee_db
      db-username: root
      db-password: admin
    depends_on:
      - db
    restart: always