version: '3'
services:
  api:
    container_name: budgee_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./target:/app/target" 
    depends_on:
      - database
    networks: 
      - api

  database:
    container_name: budgee_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - api

  client:
    container_name: budgee_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/var/www/client
    ports:
      - "3000:3000"
    networks:
      - client

networks:
  api:
  client: