version: '3'
services:
  api:
    container_name: budgee_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./target:/app/target" 
    depends_on:
      - database
    networks: 
      - api

  database:
    container_name: budgee_database
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}  # Change to the PostgreSQL environment variable for the database name
      POSTGRES_USER: ${POSTGRES_USER}  # Change to the PostgreSQL environment variable for the username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Change to the PostgreSQL environment variable for the password
    ports:
      - "5432:5432"  # Change to the default PostgreSQL port
    networks:
      - api

  client:
    container_name: budgee_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/var/www/client
    ports:
      - "3000:3000"
    networks:
      - client

networks:
  api:
  client: