spring:
  application:
    name: budgee
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 70dd7c3d0a3b0d6f43fd
            client-secret: 4ba77a15c3a53df0b87866b8fd407ac24b5b8c03

  datasource:
    url: jdbc:postgresql://localhost:5432/budgee?useSSL=false
    username: user
    password: passwd

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: "${SHOW_SQL:true}"
    properties:
      hibernate:
        "[format_sql]": true
    open-in-view: false


  liquibase:
    change-log: "classpath:db/master.xml"

springdoc:
  swagger-ui:
    oauth:
      client-id: public