spring:
  application:
    name: budgee

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "${SHOW_SQL:true}"
    properties:
      hibernate:
        "[format_sql]": true
    open-in-view: false

server:
  port: "${SERVER_PORT:8080}"
  forward-headers-strategy: native
  error:
    include-message: always

springdoc:
  swagger-ui:
    oauth:
      client-id: public