spring:
  application:
    name: budgee

  datasource:
    url: jdbc:mysql://localhost:3306/budgee?useSSL=false
    username: user
    password: passwd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: "${SHOW_SQL:true}"
    properties:
      hibernate:
        "[format_sql]": true
    open-in-view: false

springdoc:
  swagger-ui:
    oauth:
      client-id: public