package pl.budgee.domain.model;

public enum ExpenseType {

  EXPENSE_FOOD,
  EXPENSE_UTILITIES,
  EXPENSE_INSURANCE,
  EXPENSE_TRAVEL,
  EXPENSE_TAXES,
  EXPENSE_SUBSCRIPTIONS,
  EXPENSE_CLOTHING,
  EXPENSE_HEALTHCARE,
  EXPENSE_ENTERTAINMENT,
  EXPENSE_TRANSPORT,
  EXPENSE_EDUCATION

}
